/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppMapDemoRouteImport } from './routes/_app/map-demo'
import { Route as AppMapRouteImport } from './routes/_app/map'
import { Route as AppListingsRouteImport } from './routes/_app/listings'
import { Route as AppListingsIdRouteImport } from './routes/_app/listings_.$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppMapDemoRoute = AppMapDemoRouteImport.update({
  id: '/map-demo',
  path: '/map-demo',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsRoute = AppListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => AppRoute,
} as any)
const AppListingsIdRoute = AppListingsIdRouteImport.update({
  id: '/listings_/$id',
  path: '/listings/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/listings': typeof AppListingsRoute
  '/map': typeof AppMapRoute
  '/map-demo': typeof AppMapDemoRoute
  '/listings/$id': typeof AppListingsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/listings': typeof AppListingsRoute
  '/map': typeof AppMapRoute
  '/map-demo': typeof AppMapDemoRoute
  '/listings/$id': typeof AppListingsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/listings': typeof AppListingsRoute
  '/_app/map': typeof AppMapRoute
  '/_app/map-demo': typeof AppMapDemoRoute
  '/_app/listings_/$id': typeof AppListingsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/listings' | '/map' | '/map-demo' | '/listings/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/listings' | '/map' | '/map-demo' | '/listings/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/listings'
    | '/_app/map'
    | '/_app/map-demo'
    | '/_app/listings_/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/map-demo': {
      id: '/_app/map-demo'
      path: '/map-demo'
      fullPath: '/map-demo'
      preLoaderRoute: typeof AppMapDemoRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings': {
      id: '/_app/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof AppListingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/listings_/$id': {
      id: '/_app/listings_/$id'
      path: '/listings/$id'
      fullPath: '/listings/$id'
      preLoaderRoute: typeof AppListingsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppListingsRoute: typeof AppListingsRoute
  AppMapRoute: typeof AppMapRoute
  AppMapDemoRoute: typeof AppMapDemoRoute
  AppListingsIdRoute: typeof AppListingsIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppListingsRoute: AppListingsRoute,
  AppMapRoute: AppMapRoute,
  AppMapDemoRoute: AppMapDemoRoute,
  AppListingsIdRoute: AppListingsIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
